using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System.Collections.Generic;
using Turmenic.DataAccess.EntityFrameworkCore.Config;
using Turmenic.DataAccess.EntityFrameworkCore.EntityConfigurators;
using Turmenic.DataAccess.Sqlite.Test.Console.App.Entities;

namespace Turmenic.DataAccess.Sqlite.Test.Console.App.Components
{
    public class ModelConfigurator : ModelConfiguratorBase
    {
        public ModelConfigurator(ModelBuilder modelBuilder) : base(modelBuilder)
        {
        }

        protected override void AddEntityConfigurators(List<EntityCfgBase> entityConfigurators)
        {
            entityConfigurators.Add(new CountryEntityCfg(this.ModelBuilder.Entity<Country>()));
        }
    }

    public class CountryEntityCfg : DbAutoGeneratedPkNamedEntityCfg<Country, int>
    {
        public CountryEntityCfg(EntityTypeBuilder<Country> entityTypeBuilder) : base(entityTypeBuilder)
        {
        }
    }
}
