using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using Turmenic.DataAccess.EntityFrameworkCore.Entities;

namespace Turmenic.DataAccess.EntityFrameworkCore.Config
{
    public abstract class EntityCfgBase
    {
        public abstract void Configure();
    }

    public abstract class EntityCfgBase<TEntity, TEntityId, TCfgOpts> : EntityCfgBase where TEntity : EntityBase<TEntityId>
        where TCfgOpts : EntityCfgOpts<TEntity, TEntityId>
    {
        protected readonly EntityTypeBuilder<TEntity> EntityTypeBuilder;
        protected readonly TCfgOpts EntityCfgOptions;

        public EntityCfgBase(EntityTypeBuilder<TEntity> entityTypeBuilder, TCfgOpts entityCfgOptions)
        {
            this.EntityTypeBuilder = entityTypeBuilder;
            this.EntityCfgOptions = entityCfgOptions;
        }

        public override void Configure()
        {
            this.Configure(this.EntityTypeBuilder);
        }

        protected abstract void Configure(EntityTypeBuilder<TEntity> entityTypeBuilder);
    }

    public abstract class DefaultPkEntityCfgBase<TEntity, TEntityId, TCfgOpts>
        : EntityCfgBase<TEntity, TEntityId, TCfgOpts> where TEntity : EntityBase<TEntityId>
        where TCfgOpts : EntityCfgOpts<TEntity, TEntityId>
    {
        public DefaultPkEntityCfgBase(EntityTypeBuilder<TEntity> entityTypeBuilder, TCfgOpts entityCfgOptions)
            : base(entityTypeBuilder, entityCfgOptions)
        {
        }

        protected override void Configure(EntityTypeBuilder<TEntity> entityTypeBuilder)
        {
            entityTypeBuilder.HasKey(e => e.Id);
        }
    }

    public abstract class CustomGeneratedPkEntityCfgBase<TEntity, TEntityId, TCfgOpts>
        : DefaultPkEntityCfgBase<TEntity, TEntityId, TCfgOpts> where TEntity : EntityBase<TEntityId>
        where TCfgOpts : EntityCfgOpts<TEntity, TEntityId>
    {
        public CustomGeneratedPkEntityCfgBase(EntityTypeBuilder<TEntity> entityTypeBuilder, TCfgOpts entityCfgOptions)
            : base(entityTypeBuilder, entityCfgOptions)
        {
        }

        protected override void Configure(EntityTypeBuilder<TEntity> entityTypeBuilder)
        {
            base.Configure(entityTypeBuilder);

            entityTypeBuilder.Property(e => e.Id).ValueGeneratedNever();
        }
    }

    public abstract class DbAutoGeneratedPkEntityCfgBase<TEntity, TEntityId, TCfgOpts>
        : DefaultPkEntityCfgBase<TEntity, TEntityId, TCfgOpts>
        where TEntity : EntityBase<TEntityId>
        where TEntityId : struct
        where TCfgOpts : EntityCfgOpts<TEntity, TEntityId>
    {
        public DbAutoGeneratedPkEntityCfgBase(EntityTypeBuilder<TEntity> entityTypeBuilder, TCfgOpts entityCfgOptions)
            : base(entityTypeBuilder, entityCfgOptions)
        {
        }

        protected override void Configure(EntityTypeBuilder<TEntity> entityTypeBuilder)
        {
            base.Configure(entityTypeBuilder);

            entityTypeBuilder.Property(e => e.Id).ValueGeneratedOnAdd();
        }
    }

    public abstract class ClientAutoGeneratedPkEntityCfgBase<TEntity, TEntityId, TCfgOpts, TPkValueGenerator>
        : DefaultPkEntityCfgBase<TEntity, TEntityId, TCfgOpts>
        where TEntity : EntityBase<TEntityId>
        where TCfgOpts : EntityCfgOpts<TEntity, TEntityId>
        where TPkValueGenerator : ValueGenerator
    {
        public ClientAutoGeneratedPkEntityCfgBase(EntityTypeBuilder<TEntity> entityTypeBuilder, TCfgOpts entityCfgOptions)
            : base(entityTypeBuilder, entityCfgOptions)
        {
        }

        protected override void Configure(EntityTypeBuilder<TEntity> entityTypeBuilder)
        {
            base.Configure(entityTypeBuilder);

            entityTypeBuilder.Property(e => e.Id).HasValueGenerator<TPkValueGenerator>().ValueGeneratedOnAdd();
        }
    }

    public abstract class ClientAutoGeneratedStringPkEntityCfgBase<TEntity, TCfgOpts>
        : ClientAutoGeneratedPkEntityCfgBase<TEntity, string, TCfgOpts, StringPkValueGenerator>
        where TEntity : EntityBase<string>
        where TCfgOpts : EntityCfgOpts<TEntity, string>
    {
        public ClientAutoGeneratedStringPkEntityCfgBase(EntityTypeBuilder<TEntity> entityTypeBuilder, TCfgOpts entityCfgOptions)
            : base(entityTypeBuilder, entityCfgOptions)
        {
        }
    }
}
