using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using Turmenic.DataAccess.EntityFrameworkCore.Config;
using Turmenic.DataAccess.EntityFrameworkCore.Entities;

namespace Turmenic.DataAccess.EntityFrameworkCore.EntityConfigurators
{
    public class DefaultPkEntityI18nCfg<TEntity, TEntityId, TEntityName, TEntityNameId, TCfgOpts> : DefaultPkEntityCfgBase<TEntity, TEntityId, TCfgOpts>
        where TEntity : EntityI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TEntityName : EntityNameI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TCfgOpts : EntityI18nCfgOpts<TEntity, TEntityId, TEntityName, TEntityNameId>
    {
        public DefaultPkEntityI18nCfg(
            EntityTypeBuilder<TEntity> entityTypeBuilder,
            TCfgOpts entityCfgOptions)
            : base(entityTypeBuilder, entityCfgOptions)
        {
        }
    }

    public class CustomGeneratedPkEntityI18nCfg<TEntity, TEntityId, TEntityName, TEntityNameId, TCfgOpts> : CustomGeneratedPkEntityCfgBase<TEntity, TEntityId, TCfgOpts>
        where TEntity : EntityI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TEntityName : EntityNameI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TCfgOpts : EntityI18nCfgOpts<TEntity, TEntityId, TEntityName, TEntityNameId>
    {
        public CustomGeneratedPkEntityI18nCfg(
            EntityTypeBuilder<TEntity> entityTypeBuilder,
            TCfgOpts entityCfgOptions)
            : base(entityTypeBuilder, entityCfgOptions)
        {
        }
    }

    public class DbAutoGeneratedPkEntityI18nCfg<TEntity, TEntityId, TEntityName, TEntityNameId, TCfgOpts> : DbAutoGeneratedPkEntityCfgBase<TEntity, TEntityId, TCfgOpts>
        where TEntity : EntityI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TEntityName : EntityNameI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TEntityId : struct
        where TCfgOpts : EntityI18nCfgOpts<TEntity, TEntityId, TEntityName, TEntityNameId>
    {
        public DbAutoGeneratedPkEntityI18nCfg(
            EntityTypeBuilder<TEntity> entityTypeBuilder,
            TCfgOpts entityCfgOptions)
            : base(entityTypeBuilder, entityCfgOptions)
        {
        }
    }

    public class ClientAutoGeneratedPkEntityI18nCfg<TEntity, TEntityId, TEntityName, TEntityNameId, TCfgOpts, TValueGenerator> : ClientAutoGeneratedPkEntityCfgBase<TEntity, TEntityId, TCfgOpts, TValueGenerator>
        where TEntity : EntityI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TEntityName : EntityNameI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TCfgOpts : EntityI18nCfgOpts<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TValueGenerator : ValueGenerator
    {
        public ClientAutoGeneratedPkEntityI18nCfg(
            EntityTypeBuilder<TEntity> entityTypeBuilder,
            TCfgOpts entityCfgOptions)
            : base(entityTypeBuilder, entityCfgOptions)
        {
        }
    }

    public class ClientAutoGeneratedStringPkEntityI18nCfg<TEntity, TEntityName, TEntityNameId, TCfgOpts> : ClientAutoGeneratedStringPkEntityCfgBase<TEntity, TCfgOpts>
        where TEntity : EntityI18nBase<TEntity, string, TEntityName, TEntityNameId>
        where TEntityName : EntityNameI18nBase<TEntity, string, TEntityName, TEntityNameId>
        where TCfgOpts : EntityI18nCfgOpts<TEntity, string, TEntityName, TEntityNameId>
    {
        public ClientAutoGeneratedStringPkEntityI18nCfg(
            EntityTypeBuilder<TEntity> entityTypeBuilder,
            TCfgOpts entityCfgOptions)
            : base(entityTypeBuilder, entityCfgOptions)
        {
        }
    }
}
