using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using Turmenic.DataAccess.EntityFrameworkCore.Config;
using Turmenic.DataAccess.EntityFrameworkCore.Entities;

namespace Turmenic.DataAccess.EntityFrameworkCore.EntityConfigurators
{
    public class DefaultPkEntityNameI18nCfg<TEntity, TEntityId, TEntityName, TEntityNameId> : DefaultPkEntityCfgBase<TEntityName, TEntityNameId>
        where TEntity : EntityI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TEntityName : EntityNameI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
    {
        public DefaultPkEntityNameI18nCfg(EntityTypeBuilder<TEntityName> entityTypeBuilder) : base(entityTypeBuilder)
        {
        }

        protected override void Configure(EntityTypeBuilder<TEntityName> entityTypeBuilder)
        {
            base.Configure(entityTypeBuilder);

            HelperMethods.AddEntityNameI18nConfig<TEntity, TEntityId, TEntityName, TEntityNameId>(entityTypeBuilder);
        }
    }

    public class CustomGeneratedPkEntityNameI18nCfg<TEntity, TEntityId, TEntityName, TEntityNameId> : CustomGeneratedPkEntityCfgBase<TEntityName, TEntityNameId>
        where TEntity : EntityI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TEntityName : EntityNameI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
    {
        public CustomGeneratedPkEntityNameI18nCfg(EntityTypeBuilder<TEntityName> entityTypeBuilder) : base(entityTypeBuilder)
        {
        }

        protected override void Configure(EntityTypeBuilder<TEntityName> entityTypeBuilder)
        {
            base.Configure(entityTypeBuilder);

            HelperMethods.AddEntityNameI18nConfig<TEntity, TEntityId, TEntityName, TEntityNameId>(entityTypeBuilder);
        }
    }

    public class DbAutoGeneratedPkEntityNameI18nCfg<TEntity, TEntityId, TEntityName, TEntityNameId> : DbAutoGeneratedPkEntityCfgBase<TEntityName, TEntityNameId>
        where TEntity : EntityI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TEntityName : EntityNameI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TEntityNameId : struct
    {
        public DbAutoGeneratedPkEntityNameI18nCfg(EntityTypeBuilder<TEntityName> entityTypeBuilder) : base(entityTypeBuilder)
        {
        }

        protected override void Configure(EntityTypeBuilder<TEntityName> entityTypeBuilder)
        {
            base.Configure(entityTypeBuilder);

            HelperMethods.AddEntityNameI18nConfig<TEntity, TEntityId, TEntityName, TEntityNameId>(entityTypeBuilder);
        }
    }

    public class ClientAutoGeneratedPkEntityNameI18nCfg<TEntity, TEntityId, TEntityName, TEntityNameId, TValueGenerator> : ClientAutoGeneratedPkEntityCfgBase<TEntityName, TEntityNameId, TValueGenerator>
        where TEntity : EntityI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TEntityName : EntityNameI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TValueGenerator : ValueGenerator
    {
        public ClientAutoGeneratedPkEntityNameI18nCfg(EntityTypeBuilder<TEntityName> entityTypeBuilder) : base(entityTypeBuilder)
        {
        }

        protected override void Configure(EntityTypeBuilder<TEntityName> entityTypeBuilder)
        {
            base.Configure(entityTypeBuilder);

            HelperMethods.AddEntityNameI18nConfig<TEntity, TEntityId, TEntityName, TEntityNameId>(entityTypeBuilder);
        }
    }

    public class ClientAutoGeneratedStringPkEntityNameI18nCfg<TEntity, TEntityId, TEntityName> : ClientAutoGeneratedStringPkEntityCfgBase<TEntityName>
        where TEntity : EntityI18nBase<TEntity, TEntityId, TEntityName, string>
        where TEntityName : EntityNameI18nBase<TEntity, TEntityId, TEntityName, string>
    {
        public ClientAutoGeneratedStringPkEntityNameI18nCfg(EntityTypeBuilder<TEntityName> entityTypeBuilder) : base(entityTypeBuilder)
        {
        }

        protected override void Configure(EntityTypeBuilder<TEntityName> entityTypeBuilder)
        {
            base.Configure(entityTypeBuilder);

            HelperMethods.AddEntityNameI18nConfig<TEntity, TEntityId, TEntityName, string>(entityTypeBuilder);
        }
    }
}
