using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using Turmenic.DataAccess.EntityFrameworkCore.Config;
using Turmenic.DataAccess.EntityFrameworkCore.Entities;

namespace Turmenic.DataAccess.EntityFrameworkCore.EntityConfigurators
{
    public class DefaultPkEntityI18nCfg<TEntity, TEntityId, TEntityName, TEntityNameId> : DefaultPkEntityCfgBase<TEntity, TEntityId>
        where TEntity : EntityI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TEntityName : EntityNameI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
    {
        public DefaultPkEntityI18nCfg(EntityTypeBuilder<TEntity> entityTypeBuilder) : base(entityTypeBuilder)
        {
        }

        protected override void Configure(EntityTypeBuilder<TEntity> entityTypeBuilder)
        {
            base.Configure(entityTypeBuilder);
        }
    }

    public class CustomGeneratedPkEntityI18nCfg<TEntity, TEntityId, TEntityName, TEntityNameId> : CustomGeneratedPkEntityCfgBase<TEntity, TEntityId>
        where TEntity : EntityI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TEntityName : EntityNameI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
    {
        public CustomGeneratedPkEntityI18nCfg(EntityTypeBuilder<TEntity> entityTypeBuilder) : base(entityTypeBuilder)
        {
        }
    }

    public class DbAutoGeneratedPkEntityI18nCfg<TEntity, TEntityId, TEntityName, TEntityNameId> : DbAutoGeneratedPkEntityCfgBase<TEntity, TEntityId>
        where TEntity : EntityI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TEntityName : EntityNameI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TEntityId : struct
    {
        public DbAutoGeneratedPkEntityI18nCfg(EntityTypeBuilder<TEntity> entityTypeBuilder) : base(entityTypeBuilder)
        {
        }
    }

    public class ClientAutoGeneratedPkEntityI18nCfg<TEntity, TEntityId, TEntityName, TEntityNameId, TValueGenerator> : ClientAutoGeneratedPkEntityCfgBase<TEntity, TEntityId, TValueGenerator>
        where TEntity : EntityI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TEntityName : EntityNameI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TValueGenerator : ValueGenerator
    {
        public ClientAutoGeneratedPkEntityI18nCfg(EntityTypeBuilder<TEntity> entityTypeBuilder) : base(entityTypeBuilder)
        {
        }
    }

    public class ClientAutoGeneratedStringPkEntityI18nCfg<TEntity, TEntityName, TEntityNameId> : ClientAutoGeneratedStringPkEntityCfgBase<TEntity>
        where TEntity : EntityI18nBase<TEntity, string, TEntityName, TEntityNameId>
        where TEntityName : EntityNameI18nBase<TEntity, string, TEntityName, TEntityNameId>
    {
        public ClientAutoGeneratedStringPkEntityI18nCfg(EntityTypeBuilder<TEntity> entityTypeBuilder) : base(entityTypeBuilder)
        {
        }
    }
}
