using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using Turmenic.DataAccess.EntityFrameworkCore.Entities;

namespace Turmenic.DataAccess.EntityFrameworkCore.EntityConfigurators
{
    public class DefaultPkEnumEntityI18nCfg<TEntity, TEntityId, TEntityName, TEntityNameId> : DefaultPkEnumEntityCfg<TEntity, TEntityId>
        where TEntity : EnumEntityI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TEntityName : EnumEntityNameI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
    {
        public DefaultPkEnumEntityI18nCfg(EntityTypeBuilder<TEntity> entityTypeBuilder) : base(entityTypeBuilder)
        {
        }

        protected override void Configure(EntityTypeBuilder<TEntity> entityTypeBuilder)
        {
            base.Configure(entityTypeBuilder);
        }
    }

    public class CustomGeneratedPkEnumEntityI18nCfg<TEntity, TEntityId, TEntityName, TEntityNameId> : CustomGeneratedPkEnumEntityCfg<TEntity, TEntityId>
        where TEntity : EnumEntityI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TEntityName : EnumEntityNameI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
    {
        public CustomGeneratedPkEnumEntityI18nCfg(EntityTypeBuilder<TEntity> entityTypeBuilder) : base(entityTypeBuilder)
        {
        }
    }

    public class DbAutoGeneratedPkEnumEntityI18nCfg<TEntity, TEntityId, TEntityName, TEntityNameId> : DbAutoGeneratedPkEnumEntityCfg<TEntity, TEntityId>
        where TEntity : EnumEntityI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TEntityName : EnumEntityNameI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TEntityId : struct
    {
        public DbAutoGeneratedPkEnumEntityI18nCfg(EntityTypeBuilder<TEntity> entityTypeBuilder) : base(entityTypeBuilder)
        {
        }
    }

    public class ClientAutoGeneratedPkEnumEntityI18nCfg<TEntity, TEntityId, TEntityName, TEntityNameId, TValueGenerator> : ClientAutoGeneratedPkEnumEntityCfg<TEntity, TEntityId, TValueGenerator>
        where TEntity : EnumEntityI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TEntityName : EnumEntityNameI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TValueGenerator : ValueGenerator
    {
        public ClientAutoGeneratedPkEnumEntityI18nCfg(EntityTypeBuilder<TEntity> entityTypeBuilder) : base(entityTypeBuilder)
        {
        }
    }

    public class ClientAutoGeneratedStringPkEnumEntityI18nCfg<TEntity, TEntityName, TEntityNameId> : ClientAutoGeneratedStringPkEnumEntityCfg<TEntity>
        where TEntity : EnumEntityI18nBase<TEntity, string, TEntityName, TEntityNameId>
        where TEntityName : EnumEntityNameI18nBase<TEntity, string, TEntityName, TEntityNameId>
    {
        public ClientAutoGeneratedStringPkEnumEntityI18nCfg(EntityTypeBuilder<TEntity> entityTypeBuilder) : base(entityTypeBuilder)
        {
        }
    }
}
