using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using Turmenic.DataAccess.EntityFrameworkCore.Config;
using Turmenic.DataAccess.EntityFrameworkCore.Entities;

namespace Turmenic.DataAccess.EntityFrameworkCore.EntityConfigurators
{
    public class DefaultPkEnumEntityI18nCfg<TEntity, TEntityId, TEntityName, TEntityNameId, TCfgOpts>
        : DefaultPkEnumEntityCfg<TEntity, TEntityId, TCfgOpts>
        where TEntity : EnumEntityI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TEntityName : EnumEntityNameI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TCfgOpts : EnumEntityI18nCfgOpts<TEntity, TEntityId, TEntityName, TEntityNameId>
    {
        public DefaultPkEnumEntityI18nCfg(
            EntityTypeBuilder<TEntity> entityTypeBuilder,
            TCfgOpts entityCfgOptions)
            : base(entityTypeBuilder, entityCfgOptions)
        {
        }

        protected override void Configure(EntityTypeBuilder<TEntity> entityTypeBuilder)
        {
            base.Configure(entityTypeBuilder);
        }
    }

    public class CustomGeneratedPkEnumEntityI18nCfg<TEntity, TEntityId, TEntityName, TEntityNameId, TCfgOpts>
        : CustomGeneratedPkEnumEntityCfg<TEntity, TEntityId, TCfgOpts>
        where TEntity : EnumEntityI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TEntityName : EnumEntityNameI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TCfgOpts : EnumEntityI18nCfgOpts<TEntity, TEntityId, TEntityName, TEntityNameId>
    {
        public CustomGeneratedPkEnumEntityI18nCfg(
            EntityTypeBuilder<TEntity> entityTypeBuilder,
            TCfgOpts entityCfgOptions)
            : base(entityTypeBuilder, entityCfgOptions)
        {
        }
    }

    public class DbAutoGeneratedPkEnumEntityI18nCfg<TEntity, TEntityId, TEntityName, TEntityNameId, TCfgOpts>
        : DbAutoGeneratedPkEnumEntityCfg<TEntity, TEntityId, TCfgOpts>
        where TEntity : EnumEntityI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TEntityName : EnumEntityNameI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TEntityId : struct
        where TCfgOpts : EnumEntityI18nCfgOpts<TEntity, TEntityId, TEntityName, TEntityNameId>
    {
        public DbAutoGeneratedPkEnumEntityI18nCfg(
            EntityTypeBuilder<TEntity> entityTypeBuilder,
            TCfgOpts entityCfgOptions)
            : base(entityTypeBuilder, entityCfgOptions)
        {
        }
    }

    public class ClientAutoGeneratedPkEnumEntityI18nCfg<TEntity, TEntityId, TEntityName, TEntityNameId, TCfgOpts, TValueGenerator>
        : ClientAutoGeneratedPkEnumEntityCfg<TEntity, TEntityId, TCfgOpts, TValueGenerator>
        where TEntity : EnumEntityI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TEntityName : EnumEntityNameI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TCfgOpts : EnumEntityI18nCfgOpts<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TValueGenerator : ValueGenerator
    {
        public ClientAutoGeneratedPkEnumEntityI18nCfg(
            EntityTypeBuilder<TEntity> entityTypeBuilder,
            TCfgOpts entityCfgOptions)
            : base(entityTypeBuilder, entityCfgOptions)
        {
        }
    }

    public class ClientAutoGeneratedStringPkEnumEntityI18nCfg<TEntity, TEntityName, TEntityNameId, TCfgOpts>
        : ClientAutoGeneratedStringPkEnumEntityCfg<TEntity, TCfgOpts>
        where TEntity : EnumEntityI18nBase<TEntity, string, TEntityName, TEntityNameId>
        where TEntityName : EnumEntityNameI18nBase<TEntity, string, TEntityName, TEntityNameId>
        where TCfgOpts : EnumEntityI18nCfgOpts<TEntity, string, TEntityName, TEntityNameId>
    {
        public ClientAutoGeneratedStringPkEnumEntityI18nCfg(
            EntityTypeBuilder<TEntity> entityTypeBuilder,
            TCfgOpts entityCfgOptions)
            : base(entityTypeBuilder, entityCfgOptions)
        {
        }
    }
}
