using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using Turmenic.DataAccess.EntityFrameworkCore.Config;
using Turmenic.DataAccess.EntityFrameworkCore.Entities;

namespace Turmenic.DataAccess.EntityFrameworkCore.EntityConfigurators
{
    public class DefaultPkEnumEntityNameI18nCfg<TEntity, TEntityId, TEntityName, TEntityNameId> : DefaultPkEntityCfgBase<TEntityName, TEntityNameId>
        where TEntity : EnumEntityI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TEntityName : EnumEntityNameI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
    {
        public DefaultPkEnumEntityNameI18nCfg(EntityTypeBuilder<TEntityName> entityTypeBuilder) : base(entityTypeBuilder)
        {
        }

        protected override void Configure(EntityTypeBuilder<TEntityName> entityTypeBuilder)
        {
            base.Configure(entityTypeBuilder);

            HelperMethods.AddEnumEntityNameI18nConfig<TEntity, TEntityId, TEntityName, TEntityNameId>(entityTypeBuilder);
        }
    }

    public class CustomGeneratedPkEnumEntityNameI18nCfg<TEntity, TEntityId, TEntityName, TEntityNameId> : CustomGeneratedPkEntityCfgBase<TEntityName, TEntityNameId>
        where TEntity : EnumEntityI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TEntityName : EnumEntityNameI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
    {
        public CustomGeneratedPkEnumEntityNameI18nCfg(EntityTypeBuilder<TEntityName> entityTypeBuilder) : base(entityTypeBuilder)
        {
        }

        protected override void Configure(EntityTypeBuilder<TEntityName> entityTypeBuilder)
        {
            base.Configure(entityTypeBuilder);

            HelperMethods.AddEnumEntityNameI18nConfig<TEntity, TEntityId, TEntityName, TEntityNameId>(entityTypeBuilder);
        }
    }

    public class DbAutoGeneratedPkEnumEntityNameI18nCfg<TEntity, TEntityId, TEntityName, TEntityNameId> : DbAutoGeneratedPkEntityCfgBase<TEntityName, TEntityNameId>
        where TEntity : EnumEntityI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TEntityName : EnumEntityNameI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TEntityNameId : struct
    {
        public DbAutoGeneratedPkEnumEntityNameI18nCfg(EntityTypeBuilder<TEntityName> entityTypeBuilder) : base(entityTypeBuilder)
        {
        }

        protected override void Configure(EntityTypeBuilder<TEntityName> entityTypeBuilder)
        {
            base.Configure(entityTypeBuilder);

            HelperMethods.AddEnumEntityNameI18nConfig<TEntity, TEntityId, TEntityName, TEntityNameId>(entityTypeBuilder);
        }
    }

    public class ClientAutoGeneratedPkEnumEntityNameI18nCfg<TEntity, TEntityId, TEntityName, TEntityNameId, TValueGenerator>
        : ClientAutoGeneratedPkEntityCfgBase<TEntityName, TEntityNameId, TValueGenerator>
        where TEntity : EnumEntityI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TEntityName : EnumEntityNameI18nBase<TEntity, TEntityId, TEntityName, TEntityNameId>
        where TValueGenerator : ValueGenerator
    {
        public ClientAutoGeneratedPkEnumEntityNameI18nCfg(EntityTypeBuilder<TEntityName> entityTypeBuilder) : base(entityTypeBuilder)
        {
        }

        protected override void Configure(EntityTypeBuilder<TEntityName> entityTypeBuilder)
        {
            base.Configure(entityTypeBuilder);

            HelperMethods.AddEnumEntityNameI18nConfig<TEntity, TEntityId, TEntityName, TEntityNameId>(entityTypeBuilder);
        }
    }

    public class ClientAutoGeneratedStringPkEnumEntityNameI18nCfg<TEntity, TEntityId, TEntityName> : ClientAutoGeneratedStringPkEntityCfgBase<TEntityName>
        where TEntity : EnumEntityI18nBase<TEntity, TEntityId, TEntityName, string>
        where TEntityName : EnumEntityNameI18nBase<TEntity, TEntityId, TEntityName, string>
    {
        public ClientAutoGeneratedStringPkEnumEntityNameI18nCfg(EntityTypeBuilder<TEntityName> entityTypeBuilder) : base(entityTypeBuilder)
        {
        }

        protected override void Configure(EntityTypeBuilder<TEntityName> entityTypeBuilder)
        {
            base.Configure(entityTypeBuilder);

            HelperMethods.AddEnumEntityNameI18nConfig<TEntity, TEntityId, TEntityName, string>(entityTypeBuilder);
        }
    }
}
