using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Turmenic.DataAccess.EntityFrameworkCore.Config;
using Turmenic.DataAccess.EntityFrameworkCore.Entities;

namespace Turmenic.DataAccess.EntityFrameworkCore.EntityConfigurators
{
    public class LanguageI18nNameCfg : DbAutoGeneratedPkEnumEntityNameI18nCfg<LanguageI18n, short, LanguageI18nName, int, LanguageI18nNameCfgOpts>
    {
        public LanguageI18nNameCfg(EntityTypeBuilder<LanguageI18nName> entityTypeBuilder, LanguageI18nNameCfgOpts languageI18nNameCfgOpts)
            : base(entityTypeBuilder, languageI18nNameCfgOpts)
        {
        }

        protected override void Configure(EntityTypeBuilder<LanguageI18nName> entityTypeBuilder)
        {
            base.Configure(entityTypeBuilder);
        }
    }
}
