using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Turmenic.DataAccess.EntityFrameworkCore.Config;
using Turmenic.DataAccess.EntityFrameworkCore.Entities;

namespace Turmenic.DataAccess.EntityFrameworkCore.EntityConfigurators
{
    public class LanguageI18nNameCfg : DbAutoGeneratedPkEntityCfgBase<LanguageI18nName, int>
    {
        public LanguageI18nNameCfg(EntityTypeBuilder<LanguageI18nName> entityTypeBuilder) : base(entityTypeBuilder)
        {
        }

        protected override void Configure(EntityTypeBuilder<LanguageI18nName> entityTypeBuilder)
        {
            base.Configure(entityTypeBuilder);
        }
    }
}
