using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Turmenic.DataAccess.EntityFrameworkCore.Config;
using Turmenic.DataAccess.EntityFrameworkCore.Entities;

namespace Turmenic.DataAccess.EntityFrameworkCore.EntityConfigurators
{
    public class LanguageI18nCfg : DbAutoGeneratedPkEntityCfgBase<LanguageI18n, short>
    {
        public LanguageI18nCfg(EntityTypeBuilder<LanguageI18n> entityTypeBuilder) : base(entityTypeBuilder)
        {
        }

        protected override void Configure(EntityTypeBuilder<LanguageI18n> entityTypeBuilder)
        {
            base.Configure(entityTypeBuilder);
        }
    }
}
