using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Turmenic.DataAccess.EntityFrameworkCore.Entities;

namespace Turmenic.DataAccess.EntityFrameworkCore.EntityConfigurators
{
    public class LanguageI18nCfg : DbAutoGeneratedPkNamedEnumEntityI18nCfg<LanguageI18n, short, LanguageI18nName, int>
    {
        public LanguageI18nCfg(EntityTypeBuilder<LanguageI18n> entityTypeBuilder) : base(entityTypeBuilder)
        {
        }

        protected override void Configure(EntityTypeBuilder<LanguageI18n> entityTypeBuilder)
        {
            base.Configure(entityTypeBuilder);

            entityTypeBuilder.Property(e => e.LanguageNameI18n).IsRequired();
            entityTypeBuilder.Property(e => e.LanguageCodeI18n).IsRequired();
            entityTypeBuilder.Property(e => e.IsDefaultLanguageI18n).IsRequired();
        }
    }
}
